const root=document.documentElement;
const toast=document.getElementById('toast');
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>toast.classList.remove('show'),1500)}
function setTheme(t){root.dataset.theme=t;localStorage.setItem('omid-theme-v6',t);document.querySelectorAll('.theme').forEach(b=>b.classList.toggle('active',b.dataset.theme===t));document.querySelector('meta[name="theme-color"]').content=t==='dark'?'#050b0e':'#f5fbfb'}
setTheme(localStorage.getItem('omid-theme-v6')||'dark');
document.querySelectorAll('.theme').forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));
function setLang(lang){document.documentElement.lang=lang;document.documentElement.dir=lang==='fa'?'rtl':'ltr';document.querySelectorAll('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.querySelectorAll('[data-en]').forEach(el=>el.textContent=el.dataset[lang]);localStorage.setItem('omid-lang-v6',lang)}
setLang(localStorage.getItem('omid-lang-v6')||'en');document.querySelectorAll('.lang').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));

document.querySelectorAll('.copy').forEach(btn=>btn.onclick=async()=>{try{await navigator.clipboard.writeText(btn.dataset.copy);showToast('Copied ✓')}catch{showToast('Copy failed')}});
document.getElementById('saveContact').onclick=()=>{const v=['BEGIN:VCARD','VERSION:3.0','FN:Omid Salem','N:Salem;Omid;;;','TEL;TYPE=CELL:09046870221','TEL;TYPE=ICE:+989132768702','EMAIL;TYPE=INTERNET:omidsalem113@gmail.com','URL:https://instagram.com/omid_.slm','URL:https://t.me/Omid_st116','END:VCARD'].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([v],{type:'text/vcard;charset=utf-8'}));a.download='Omid-Salem.vcf';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
const emergency=document.getElementById('emergency');emergency.onclick=()=>{const open=emergency.classList.toggle('open');emergency.setAttribute('aria-expanded',open);document.getElementById('emergencyHint').textContent=open?'0913 276 8702':(root.lang==='fa'?'برای نمایش لمس کنید':'Tap to reveal')};
const share=()=>{if(navigator.share)navigator.share({title:'Omid Salem',text:'Omid Salem — Contact Card',url:location.href}).catch(()=>{});else{navigator.clipboard?.writeText(location.href);showToast('Link copied ✓')}};document.getElementById('shareBtn').onclick=share;
function makeQR(){const box=document.getElementById('qrBox');const url=encodeURIComponent(location.href);box.innerHTML='<img alt="QR code" src="https://api.qrserver.com/v1/create-qr-code/?size=500x500&margin=12&data='+url+'">';document.getElementById('qrUrl').textContent=location.href}
document.getElementById('qrBtn').onclick=()=>{makeQR();document.getElementById('qrModal').classList.add('show');document.getElementById('qrModal').setAttribute('aria-hidden','false')};document.getElementById('qrClose').onclick=()=>{document.getElementById('qrModal').classList.remove('show');document.getElementById('qrModal').setAttribute('aria-hidden','true')};document.getElementById('qrModal').onclick=e=>{if(e.target.id==='qrModal')document.getElementById('qrClose').click()};
